base_frame: base_link
map_frame: map
odom_frame: odom

map_update_interval: 1.0
maxUrange: 6.0
maxRange: 8.0
sigma: 0.0

kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 200

srr: 0.0  # 0.01
srt: 0.0  # 0.02
str: 0.0  # 0.1
stt: 0.0  # 0.02

linearUpdate: 0.5
angularUpdate: 0.436
temporalUpdate: 1.0
resampleThreshold: 0.5
particles: 80

xmin: 0.0
ymin: 0.0
xmax: 3.0
ymax: 3.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
