<?xml version="1.0"?>

<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="chassisHeight" value="0.1"/>
    <xacro:property name="chassisLength" value="0.4"/>
    <xacro:property name="chassisWidth" value="0.2"/>
    <xacro:property name="chassisMass" value="50"/>

    <xacro:property name="casterRadius" value="0.05"/>
    <xacro:property name="casterMass" value="5"/>

    <xacro:property name="wheelWidth" value="0.05"/>
    <xacro:property name="wheelRadius" value="0.1"/>
    <xacro:property name="wheelPos" value="0.2"/>
    <xacro:property name="wheelMass" value="5"/>

    <xacro:property name="cameraSize" value="0.05"/>
    <xacro:property name="cameraMass" value="0.1"/>

    <xacro:include filename="$(find robot_description)/urdf/robot.gazebo" />
    <xacro:include filename="$(find robot_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/macros.xacro" />

    <!-- Chassis -->
    <link name="footprint" />

    <joint name="base_joint" type="fixed">
        <parent link="footprint"/>
        <child link="chassis"/>
    </joint>

    <link name="chassis">
        <collision>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <inertial>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <mass value="${chassisMass}"/>
            <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
        </inertial>
    </link>

    <!-- Caster wheel -->
    <joint name="fixed" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
    </joint>

    <link name="caster_wheel">
        <collision>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${casterRadius}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${casterRadius}"/>
            </geometry>
        </visual>

        <inertial>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <mass value="${casterMass}"/>
            <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
        </inertial>
    </link>

    <!-- Fixed wheels -->
    <wheel lr="left" tY="1"/>
    <wheel lr="right" tY="-1"/>

    <!-- Camera -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${-cameraSize+chassisLength/2} 0 ${cameraSize+wheelRadius+cameraSize/2+0.08}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="camera"/>
    </joint>

    <link name="camera">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <inertial>
            <mass value="${cameraMass}" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
        </inertial>
    </link>

    <!-- Hokuyo -->
    <joint name="hokuyo_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="${-cameraSize+chassisLength/2} 0 ${2*wheelRadius}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="hokuyo_link"/>
    </joint>

    <link name="hokuyo_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://robot_description/urdf/hokuyo.dae"/>
            </geometry>
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>


</robot>
